[build]
target = "index.html"
dist = "docs"
filehash = false
public_url = "/"

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8000
open = true

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "echo 'projects.stevenwing.dev' > $TRUNK_STAGING_DIR/CNAME"]

